# Name of the GitHub Actions workflow
name: Deploy to Render

# Trigger the workflow on push and pull request events to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  # Define a job named "deploy"
  deploy:
    # Specify the operating system to run the job on
    runs-on: ubuntu-latest
    
    # Define the steps to be executed in the job
    steps:
      - name: Checkout code
        # Checkout the code from the repository
        uses: actions/checkout@v3
      
      # Define a step named "Node.js"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '20'
      
      # Install dependencies
      - name : Install dependencies
        run: npm install
      
      # Build the app
      - name: Build App
        run: npm run build

      # Define a step named "Deploy"
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        # Set an environment variable with the deployment URL from secrets
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        # Run the deployment command
        run: |
          curl "$DEPLOY_URL"
        